name: welcome_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  path: ^1.8.0
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  csv: ^5.1.1
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/A.wav
    - assets/sounds/B.wav
    - assets/sounds/C.wav
    - assets/sounds/D.wav
    - assets/sounds/E.wav
    - assets/sounds/F.wav
    - assets/sounds/G.wav
    - assets/sounds/H.wav
    - assets/sounds/I.wav
    - assets/sounds/J.wav
    - assets/sounds/K.wav
    - assets/sounds/L.wav
    - assets/sounds/M.wav
    - assets/sounds/N.wav
    - assets/sounds/O.wav
    - assets/sounds/P.wav
    - assets/sounds/Q.wav
    - assets/sounds/R.wav
    - assets/sounds/S.wav
    - assets/sounds/T.wav
    - assets/sounds/U.wav
    - assets/sounds/V.wav
    - assets/sounds/W.wav
    - assets/sounds/X.wav
    - assets/sounds/Y.wav
    - assets/sounds/Z.wav
    - assets/sounds/success.wav
    - assets/sounds/failure.wav

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Belanosima
      fonts:
        - asset: assets/fonts/Belanosima-Regular.ttf
          weight: 400
